name: Linux CI

on:
  push:
    branches:
      - main
      - 2-setup-cicd
  pull_request:
    branches:
      - main
  workflow_dispatch

jobs:
  combined:
    name: Lint, Build, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Just
        run: cargo install just

      - name: Run Lint, Build, and Test
        run: |
          just lint
          just build
          just test
